#!/bin/bash
# acrylicctl.sh — control blur & transparency, sync to Hyprland + Waybar

# === CONFIG PATHS ===
HYPR_OUT="$HOME/.config/hypr/acrylic.conf"
WAYBAR_OUT="$HOME/.config/waybar/acrylic.css"
STATE_FILE="$HOME/.config/hypr/acrylic_state"

# === DEFAULTS ===
BLUR=5
TRANS=0.8
ACTIVE=$(echo "$TRANS + 0.05" | bc)
INACTIVE=$(echo "$TRANS - 0.05" | bc)

# Load previous state if exists
if [ -f "$STATE_FILE" ]; then
  source "$STATE_FILE"
fi

# === FUNCTIONS ===
write_files() {
  # Hyprland snippet
  cat >"$HYPR_OUT" <<EOF
# Auto-generated by acrylicctl.sh
\$blur_size = $BLUR
\$active_opacity = $ACTIVE
\$inactive_opacity = $INACTIVE
EOF

  # Waybar snippet
  cat >"$WAYBAR_OUT" <<EOF
/* Auto-generated by acrylicctl.sh */
/* @define-color blur_size ${BLUR}px; */
@define-color background_surface alpha(@surface_container, ${INACTIVE});
EOF

  # Save state
  echo "BLUR=$BLUR" >"$STATE_FILE"
  echo "TRANS=$TRANS" >>"$STATE_FILE"
}

# === COMMANDS ===
case "$1" in
get)
  echo "Blur: $BLUR | Transparency: $TRANS"
  ;;
blur)
  BLUR=$2
  hyprctl reload
  ~/.scripts/wbrestart.sh
  ;;
trans)
  TRANS=$2
  hyprctl reload
  ~/.scripts/wbrestart.sh
  ;;
*)
  echo "Usage: $0 {get|blur <val>|trans <val>}"
  exit 1
  ;;
esac

write_files
