#!/bin/bash
# acrylicctl.sh — control blur & transparency, sync to Hyprland + Waybar

# === CONFIG PATHS ===
HYPR_OUT="$HOME/.config/hypr/acrylic.conf"
WAYBAR_OUT="$HOME/.config/waybar/acrylic.css"
STATE_FILE="$HOME/.config/hypr/acrylic_state"

# === DEFAULTS ===
BLUR=5
TRANS=0.8

# Load previous state if exists
if [ -f "$STATE_FILE" ]; then
  source "$STATE_FILE"
fi

# === FUNCTIONS ===
write_files() {
  ACTIVE=$(echo "$TRANS + 0.05" | bc)
  INACTIVE=$(echo "$TRANS - 0.05" | bc)
  WAYBAR=$(echo "$TRANS - 0.1" | bc)
  # Hyprland snippet
  cat >"$HYPR_OUT" <<EOF
# Auto-generated by acrylicctl.sh
\$blur_size = $BLUR
\$active_opacity = $ACTIVE
\$inactive_opacity = $INACTIVE
EOF

  # Waybar snippet
  cat >"$WAYBAR_OUT" <<EOF
/* Auto-generated by acrylicctl.sh */
/* @define-color blur_size ${BLUR}px; */
@define-color background_surface alpha(@surface_container, ${WAYBAR});
EOF

  # Save state
  echo "BLUR=$BLUR" >"$STATE_FILE"
  echo "TRANS=$TRANS" >>"$STATE_FILE"
}

# === COMMANDS ===
case "$1" in
get)
  echo "Blur: $BLUR | Transparency: $TRANS"
  ;;
get-transparency)
  echo "$TRANS"
  ;;
get-blur)
  echo "$BLUR"
  ;;
get-values)
  echo "$TRANS $BLUR"
  ;;
blur)
  BLUR=$2
  hyprctl reload
  ~/.scripts/wbrestart.sh
  ;;
trans)
  TRANS=$2
  hyprctl reload
  ~/.scripts/wbrestart.sh
  ;;
trans+)
  TRANS=$(awk "BEGIN {print $TRANS + 0.1}")
  hyprctl reload
  ~/.scripts/wbrestart.sh
  ;;
trans-)
  TRANS=$(awk "BEGIN {print $TRANS - 0.1}")
  hyprctl reload
  ~/.scripts/wbrestart.sh
  ;;
blur+)
  BLUR=$(awk "BEGIN {print $BLUR + 1}")
  hyprctl reload
  ;;
blur-)
  BLUR=$(awk "BEGIN {print $BLUR - 1}")
  hyprctl reload
  ;;

*)
  echo "Usage: $0 {get|blur <val>|trans <val>|blur+|blur-|trans+|trans-|get-transparency|get-blur|get-values}"
  exit 1
  ;;
esac

write_files
